src/Entity/Aiku.php
<?php

namespace App\Entity;

use App\Repository\AikuRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=AikuRepository::class)
 */
class Aiku
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=1000)
     */
    private $promptNative;

    /**
     * @ORM\Column(type="string", length=1000, nullable=true)
     */
    private $prompt;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $locale;

    /**
     * @ORM\Column(type="string", length=10000, nullable=true)
     */
    private $parameters;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image_path;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_published;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="aikus")
     */
    private $author;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPromptNative(): ?string
    {
        return $this->promptNative;
    }

    public function setPromptNative(string $promptNative): self
    {
        $this->promptNative = $promptNative;

        return $this;
    }

    public function getPrompt(): ?string
    {
        return $this->prompt;
    }

    public function setPrompt(?string $prompt): self
    {
        $this->prompt = $prompt;

        return $this;
    }

    public function getLocale(): ?string
    {
        return $this->locale;
    }

    public function setLocale(?string $locale): self
    {
        $this->locale = $locale;

        return $this;
    }

    public function getParameters(): ?string
    {
        return $this->parameters;
    }

    public function setParameters(?string $parameters): self
    {
        $this->parameters = $parameters;

        return $this;
    }

    public function getImagePath(): ?string
    {
        return "assets/img/" . $this->image_path;
    }

    public function setImagePath(string $image_path): self
    {
        $this->image_path = $image_path;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $username;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lastName;

    /**
     * @ORM\OneToMany(targetEntity=Aiku::class, mappedBy="author")
     */
    private $aikus;


    public function __construct()
    {
        $this->aikus = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(?string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(?string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    /**
     * @return Collection|Aiku[]
     */
    public function getAikus(): Collection
    {
        return $this->aikus;
    }

    public function addAiku(Aiku $aiku): self
    {
        if (!$this->aikus->contains($aiku)) {
            $this->aikus[] = $aiku;
            $aiku->setAuthor($this);
        }

        return $this;
    }

    public function removeAiku(Aiku $aiku): self
    {
        if ($this->aikus->removeElement($aiku)) {
            // set the owning side to null (unless already changed)
            if ($aiku->getAuthor() === $this) {
                $aiku->setAuthor(null);
            }
        }

        return $this;
    }

    public function getName()
    {
        return $this->firstName . " " . $this->lastName;
    }

}

src/Form/AikuType.php
<?php

namespace App\Form;

use App\Entity\Aiku;

use App\Entity\User;
use App\Repository\UserRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\LocaleType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * @property UserRepository $userRepository
 */
class AikuType extends AbstractType
{
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add(
                'promptNative',
                TextareaType::class,
                [
                    'attr' => ['class' => 'textarea'],
                    'required' => true,
                ]
            )
            ->add(
                'prompt',
                TextareaType::class,
                [
                    'attr' => ['class' => 'textarea'],
                    'required' => false,
                ]
            )
            ->add(
                'locale',
                LocaleType::class,
                [
                    'data' => "DE",
                    'attr' => ['class' => 'select'],
                    'required' => false,
                ]
            )
            ->add(
                'parameters',
                TextType::class,
                [
                    'attr' => ['class' => 'input'],
                    'required' => false,
                ]
            )
            ->add(
                'imageFile',
                FileType::class,
                [
                    'mapped' => false,
                    'attr' => ['class' => 'input'],
                    'required' => false,
                ]
            )
            ->add(
                'author',
                ChoiceType::class,
                [
                    'placeholder' => 'Choose an author',
                    'choices' => $this->userRepository->findAll(),
                    'choice_label' => function(?User $user) {
                        return $user ? $user->getName() : '';
                    },
                    'attr' => ['class' => 'input'],
                    'required' => true,
                ]
            )
            ->add('isPublished',
                CheckboxType::class,
                [
                    'label_attr' => ['class' => 'checkbox'],
                    'attr' => ['type' => 'checkbox'],
                    'required' => false,
                ]
            )
            ->add(
                'submit',
                SubmitType::class,
                [
                    'attr' => ['class' => 'button is-primary']
                ]
            )
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Aiku::class,
        ]);
    }
}

src/Controller/AikuController.php
<?php

namespace App\Controller;

use App\Entity\Aiku;
use App\Form\AikuType;
use App\Repository\AikuRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class AikuController extends AbstractController
{
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    /**
     * @Route("/", name="index")
     */
    public function index(AikuRepository $aikuRepository): Response
    {
        $aikus = $aikuRepository->findAll();
        return $this->render('aiku/index.html.twig', [
            'controller_name' => 'AikuController',
            'all_aikus' => $aikus
        ]);
    }

    /**
     * @param $id
     * @param AikuRepository $aikuRepository
     * @return Response
     *
     * @Route("/{id}", name="aiku_detail", requirements={"id"="\d+"})
     */
    public function detail($id, AikuRepository $aikuRepository)
    {
        $aiku = $aikuRepository->find($id);
        return $this->render('aiku/detail.html.twig', [
            'aiku' => $aiku,
        ]);
    }

    /**
     * @param AikuRepository $aikuRepository
     * @return Response
     *
     * @Route("/aiku/new", name="aiku_new")
     */
    public function new(Request $request, UserRepository $userRepository): Response
    {
        $aiku = new Aiku();
        $form = $this->createForm(AikuType::class, $aiku);

        $this->formHandling($form, $request);

        return $this->renderForm('aiku/new.html.twig', ['form' => $form]);
    }

    /**
     * @param AikuRepository $aikuRepository
     * @return Response
     *
     * @Route("/aiku/{id}/edit", name="aiku_edit")
     */
    public function edit($id, Request $request, AikuRepository $aikuRepository): Response
    {
        $aiku = $aikuRepository->find($id);
        $form = $this->createForm(AikuType::class, $aiku);

        $this->formHandling($form, $request);

        return $this->renderForm('aiku/new.html.twig', ['form' => $form]);
    }

    public function like($id, AikuRepository $aikuRepository)
    {
        $aiku = $aikuRepository->find($id);
        $aiku->setLikes($aiku->getLikes() + 1);
        $em = $this->getDoctrine()->getManager();
        $em->persist($aiku);
        $em->flush();
        return $this->redirectToRoute('aiku_detail', ['id' => $id]);
    }

    /**
     * @param $id
     * @param AikuRepository $aikuRepository
     * @return Response
     *
     * @Route("/aiku/{id}/delete", name="aiku_delete")
     */
    public function delete($id, AikuRepository $aikuRepository): Response
    {
        $aiku = $aikuRepository->find($id);
        $em = $this->getDoctrine()->getManager();
        $em->remove($aiku);
        $em->flush();
        return $this->redirectToRoute('index');
    }

    private function formHandling($form, $request): void
    {
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Aiku $aiku */
            $aiku = $form->getData();

            /** @var UploadedFile $uploadedFile */
            $uploadedFile = $form['imageFile']->getData();
            if ($uploadedFile) {
                $destination = $this->getParameter('kernel.project_dir') . '/public/assets/img';
                $origFileName = uniqid('', true) . $uploadedFile->getClientOriginalName();
                $uploadedFile->move($destination, $origFileName);
                $aiku->setImagePath($origFileName);
            }
            $author = $this->userRepository->find($form['author']->getData());
            $aiku->setAuthor($author);
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($aiku);
            $entityManager->flush();
            $this->addFlash('success', "this worked!");


            $this->redirectToRoute('index');
        }
    }

}

templates/aiku/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AikuController!{% endblock %}

{% block body %}
    {% if aiku.isPublished or is_granted('ROLE_ADMIN')%}

    {% if not aiku.isPublished %}
        <div class="notification is-warning">
            This Aiku is not published. <strong><a href="{{ path('aiku_edit', {id: aiku.id}) }}">edit</a></strong> the Aiku to publish it
        </div>
        {% endif %}
    <div class="columns is-centered">
        <div class="column is-one-third">
        <code>
            prompts = <br><mark>'{{ aiku.promptNative |nl2br}}'</mark><br>
            author = <mark>'{{aiku.author.name}}'</mark><br>
            width =  512 <br>
            height =  512<br>
            model = "vqgan_imagenet_f16_16384" <br>
            initial_image = "/content/new Pictures 045.jpg"<br>
            target_images = ""<br>
            seed = -1<br>
            max_iterations = 10000<br>
            input_images = "" <br>

        </code>
        </div>
        <div class="column is-one-third">
            <img src="{{ aiku.imagePath }}" width="512px">
        </div>
    </div>
    {% endif %}
{% endblock %}

templates/aiku/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AikuController!{% endblock %}

{% block body %}
    <div class="columns is-multiline is-centered">
        {% for aiku in all_aikus %}
            {% if aiku.isPublished or is_granted('ROLE_ADMIN') %}
                <div class="column is-narrow">
                    <div class="card" style="width: 18rem;">
                        <div class="card-image">
                            <figure class="image is-1by1">
                                <img src="{{ aiku.imagePath }}" alt="...">
                            </figure>
                        </div>
                        <div class="card-content">
                            <div class="media">
                                <div class="media-content">
                                    <p class="title is-4">{{ aiku.author.name }}</p>
                                    <p class="subtitle is-6">@{{ aiku.author.userIdentifier }}</p>
                                </div>
                            </div>

                            <div class="content">
                                {% if not aiku.isPublished %}
                                    <span class="tag is-warning">Not Published</span><br><br>
                                {% endif %}
                                {{ aiku.promptNative }}<br>
                                <br>
                                <time datetime="2016-1-1">11:09 PM - 1 Jan 2016</time>
                            </div>
                            <footer class="card-footer">
                                <a href="{{ path('aiku_detail', {id: aiku.id}) }}" class="card-footer-item button">Go somewhere</a>
                            </footer>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

templates/aiku/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello AikuController!{% endblock %}

{% block body %}
    {{ form_start(form, {'attr': {'class': 'field'}}) }}
    <div class="my-custom-class-for-errors">
        {{ form_errors(form) }}
    </div>

    <div class="columns">
        <div class="column">
            <div class="field">
                {{ form_label(form.promptNative) }}
                {{ form_widget(form.promptNative) }}
            </div>
        </div>
        <div class="column">
            <div class="field">
                {{ form_label(form.prompt) }}
                {{ form_widget(form.prompt) }}
            </div>
        </div>
    </div>
    <div class="field">
        {{ form_label(form.author) }}
        {{ form_widget(form.author) }}
    </div>
    <div class="field">
        {{ form_label(form.locale) }}
        <div class="control">
            <div class="select">
                {{ form_widget(form.locale) }}
            </div>
        </div>
    </div>
    <div class="field">
        {{ form_label(form.parameters) }}
        {{ form_widget(form.parameters) }}
    </div>
    <div class="file has-name">
        <label class="file-label">
            <input class="file-input" type="file" name="resume">
        </label>
    </div>
    {{ form_label(form.imageFile) }}
    {{ form_widget(form.imageFile) }}
    <label class="checkbox mt-4 mb-4">
        {{ form_widget(form.isPublished) }} {{ form.isPublished.vars.name }}
    </label>
    {{ form_end(form) }}
{% endblock %}